name    'lab42-php'
version '2.0.7'
author  'Romain THERRAT'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/lermit/puppet-php'
summary 'Puppet module for php'
description 'This module installs and manages php. Check README.rdoc for details. Puppi is required for some common functions: you can install them without using the whole module. Monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'lab42/puppi', '>= 2.0.0'
dependency 'lab42/monitor', '>= 2.0.0'
dependency 'lab42/firewall', '>= 2.0.0'
